# Default initial positions for so101_new_calib's ros2_control fake system

initial_positions:
  elbow_flex: 0.0
  gripper: 0.0
  shoulder_lift: 0.0
  shoulder_pan: 0.0
  wrist_flex: 0.0
  wrist_roll: 0.0